config/routes.rb
KwWellnessfit::Application.routes.draw do


  get "news/index"
  get "news/show"
  get "labors/index"
  get "hints/index"
  get "hints/show"
  get "contacts/new"
  get "contacts/index"
  get "contacts/show"
  post "contacts/create"
  get "clients/index"
  get "cases/index"
  get "cases/show"

 resources :home
 resources :ciafisio
 resources :about
 resources :cases
 resources :works
 resources :links
 
 resources :user_sessions
 resources :users
 resources :password_resets
 resources :atualizar
 
 #Inicio do namespace Admin
 namespace(:admin){
   
   resources :downloads do
     member do
       get :baixar
     end
   end
   resources :presences 
   resources :status_presences   
   resources :companies do #Inicio das rotas vinculadas a companies
     member do
       get 'information'
     end
     resources :functionaries do
       resources :bout_functionaries
       resources :sector_functionaries
     end
     resources :bouts
     resources :sectors  
     resources(:events){
       resources :presences do
        member do
          get 'update_presences'
        end
       end
     }  

   end #Final das rotas vinculadas a companies
   
   resources :static_contents
   resources :users do
     collection do
       get 'search'
     end
   end
   
 
   root :to => "static_contents#index"
 }
 #Final do namespace Admin
 
 root :to => "home#index"
 match 'cadastro' => "users#new"
 match 'login' => 'user_sessions#new'  
 match 'logout' => 'user_sessions#destroy'
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:status_presence/:user_id(.:format)' => 'admin/presences#update_presences'
 
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:blog_id/:user_id', :controller=> 'admin/presences', :action => 'update_presences'
end

app/models/bout.rb
class Bout < ActiveRecord::Base
  belongs_to :company
  has_many :events, :dependent => :destroy
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Bout.all(:conditions => ['active =  true'])
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :functionaries, :dependent => :destroy
  has_many :bouts, :dependent => :destroy
  has_many :sectors, :dependent => :destroy
  has_many :events, :dependent => :destroy  
  #attr_accessible :company_name, :fantasy_name, :cnpj, :phone, :address, :district, :city, :state, :zip_code, :responsible, :segment, :date_visit, :email, :electronic_address, :doctor, :nurse, :security, :engineering, :rh_responsible, :rh_contact, :gymnastics, :reason_gymnastics, :quality, :map, :absenteeism, :rotation, :male_workers, :female_workers, :agreement
end

app/models/download.rb
class Download < ActiveRecord::Base
  #attr_accessible :name, :archive_file_name, :archive_content_type, :archive_file_size, :archive_updated_at
  has_attached_file :archive,
        :url => "/uploads/:attachment/:id/:basename_:style.:extension",
        :path => ":rails_root/public/uploads/:attachment/:id/:basename_:style.:extension"
        
end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :bout_id, :event_date, :employees_present, :observation,  :sector_attributes, :sector_ids
  belongs_to :bout
  belongs_to :company
  has_many :presences
  has_and_belongs_to_many :sectors
end

app/models/functionary.rb
class Functionary < ActiveRecord::Base
  belongs_to :company
  belongs_to :sector
  has_many :presences, :dependent => :destroy
  has_many :bout_functionaries, :dependent => :destroy
  has_many :sector_functionaries, :dependent => :destroy
  #attr_accessible :company_id, :sector_id, :name, :internal_code, :active, :inactivation_date, :reason, :sex
end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :functionary
  belongs_to :event
  belongs_to :status_presence
  belongs_to :sector
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  belongs_to :company
  has_many :functionaries, :dependent => :destroy
  has_many :sector_functionaries
  has_many :bout_functionaries  
  has_many :presences   
  has_and_belongs_to_many :events
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Sector.all(:conditions => ['active = true'])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :empresario
      @role = :empresario
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/admin/sectors_controller.rb
class Admin::SectorsController < ApplicationController
  layout "inadmin"
  access_control do
      allow :admin 
      allow :supervisor, :empresario, :to =>[:show]
  end
  before_filter :permission_check, :load_company
  
  def index
    @sectors = @company.sectors.all
  end

  def show
    @sector = @company.sectors.find(params[:id])
  end

  def new
    @sector = @company.sectors.build(:active => true)
  end

  def create
    @sector = @company.sectors.build(params[:sector])
    if @sector.save
      redirect_to admin_company_sector_path(@company, @sector), :notice => "Successfully created sector."
    else
      render :action => 'new'
    end
  end

  def edit
    @sector = @company.sectors.find(params[:id])
  end

  def update
    @sector = @company.sectors.find(params[:id])
    if @sector.update_attributes(params[:sector])
      redirect_to admin_company_sector_path(@company, @sector), :notice  => "Successfully updated sector."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @sector = @company.sectors.find(params[:id])
    @sector.destroy
    redirect_to admin_company_sectors_path(@company), :notice => "Successfully destroyed sector."
  end
  
  def load_company
    @company = Company.find(params[:company_id])
  end
end

app/controllers/rssreader.rb
class RssReader
  require 'rss'
  require 'open-uri'
  def self.posts_for(feed_url, length = 0, perform_validation=false, v_fonte = "")
    posts = []
    open(feed_url) do |rss|
      posts = RSS::Parser.parse(rss, perform_validation).items
    end
    if length > 0
      posts[0..length - 1] if posts.size > length
    else
      posts[0..length - 1]
    end
    
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/sectors_helper.rb
module Admin::SectorsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/sectors/_form.html.erb
<div id="Box_form">
	<%= form_for [:admin, @company,@sector] do |f| %>
	  <%= f.error_messages %>
	  <p>
	    <%= f.label :name, "Nome"%>
	    <%= f.text_field :name %>
	  </p>
	  <p>
	    <%= f.label :description, "Descrição" %><br />
	    <%= f.text_area :description %>
	  </p>
	  <p>
	    <%= f.label :active, "Ativo ?" %>
	    <%= f.check_box :active %>
	  </p>
	  <p><%= submit_tag "Voltar",:type=>"button",:onclick=>"window.open('"+admin_company_sectors_path(@company)+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%> <%= f.submit "Salvar", :class => "Bt_enviar" %></p>
	<% end %>
</div>

app/views/admin/sectors/edit.html.erb
<% title @company.company_name+" - "+ @sector.name %>

<h1><%= @company.company_name %> - <%=@sector.name%></h1><br />
<br />
<p>Utilize os campos abaixo para alterar as informações deste setor.</p><br />
<br />
<%= render 'form' %>

app/views/admin/sectors/index.html.erb
<% title @company.company_name+" - Lista de Setores" %>

<h1><%= @company.company_name %> - Setores</h1><br />
<p>Visualize abaixo a lista dos setores registrados no sistema.</p><br />
<br />
<p style="text-align: right;"><%= submit_tag "+ Criar novo",:type=>"button",:onclick=>"window.open('"+new_admin_company_sector_path(@company)+"','_self');", :class => "Bt_enviar"%> </p>
<br />
<table cellspacing="0" class="tablesorter">
  <thead> 
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Ativo</th>
    <th colspan="3" style="width:20%;">Ações</th>
  </tr>
  </thead> 
  <tbody>
  <% for sector in @sectors %>
    <tr <%='class=notactive' if !sector.active%>>
      <td><%= sector.name %></td>
      <td><%= sector.description %></td>
      <td><%= print_active(sector.active) %></td>

      <td><%= link_to "Visualizar", admin_company_sector_path(@company,sector) %></td>
      <td><%= link_to "Editar", edit_admin_company_sector_path(@company,sector) %></td>
      <td><%= link_to "Excluir", admin_company_sector_path(@company,sector), :confirm => 'Esta operação não poderá ser desfeita, deseja continuar?', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/sectors/new.html.erb
<% title @company.company_name+" - Novo Setor!" %>

<%= render 'form' %>

app/views/admin/sectors/show.html.erb
<% title @company.company_name+" - "+ @sector.name %>

<h1><%= @company.company_name %> - <%=@sector.name%></h1><br />
<br />
<p>Verifique se as informações abaixo estão corretas.</p><br />
<br />
<p>
  <strong>Nome:</strong>
  <%= @sector.name %>
</p>
<p>
  <strong>Descrição:</strong>
  <%= @sector.description %>
</p>
<p>
  <strong>Ativo?</strong>
  <%= print_active(@sector.active) %>
</p>
<br />
<br />
<br />
<p>
	<%= submit_tag "Voltar",:type=>"button",:onclick=>"window.open('"+admin_company_sectors_path(@company)+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%>
</p>