config/routes.rb
KwWellnessfit::Application.routes.draw do


  get "news/index"
  get "news/show"
  get "labors/index"
  get "hints/index"
  get "hints/show"
  get "contacts/new"
  get "contacts/index"
  get "contacts/show"
  post "contacts/create"
  get "clients/index"
  get "cases/index"
  get "cases/show"

 resources :home
 resources :ciafisio
 resources :about
 resources :cases
 resources :works
 resources :links
 
 resources :user_sessions
 resources :users
 resources :password_resets
 resources :atualizar
 
 #Inicio do namespace Admin
 namespace(:admin){
   
   resources :downloads do
     member do
       get :baixar
     end
   end
   resources :presences 
   resources :status_presences   
   resources :companies do #Inicio das rotas vinculadas a companies
     member do
       get 'information'
     end
     resources :functionaries do
       resources :bout_functionaries
       resources :sector_functionaries
     end
     resources :bouts
     resources :sectors  
     resources(:events){
       resources :presences do
        member do
          get 'update_presences'
        end
       end
     }  

   end #Final das rotas vinculadas a companies
   
   resources :static_contents
   resources :users do
     collection do
       get 'search'
     end
   end
   
 
   root :to => "static_contents#index"
 }
 #Final do namespace Admin
 
 root :to => "home#index"
 match 'cadastro' => "users#new"
 match 'login' => 'user_sessions#new'  
 match 'logout' => 'user_sessions#destroy'
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:status_presence/:user_id(.:format)' => 'admin/presences#update_presences'
 
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:blog_id/:user_id', :controller=> 'admin/presences', :action => 'update_presences'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :functionaries, :dependent => :destroy
  has_many :bouts, :dependent => :destroy
  has_many :sectors, :dependent => :destroy
  has_many :events, :dependent => :destroy  
  #attr_accessible :company_name, :fantasy_name, :cnpj, :phone, :address, :district, :city, :state, :zip_code, :responsible, :segment, :date_visit, :email, :electronic_address, :doctor, :nurse, :security, :engineering, :rh_responsible, :rh_contact, :gymnastics, :reason_gymnastics, :quality, :map, :absenteeism, :rotation, :male_workers, :female_workers, :agreement
end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :bout_id, :event_date, :employees_present, :observation,  :sector_attributes, :sector_ids
  belongs_to :bout
  belongs_to :company
  has_many :presences
  has_and_belongs_to_many :sectors
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "inadmin"
  access_control do
      allow :admin 
      allow :supervisor, :empresario, :to =>[:show]
  end
  before_filter :permission_check, :load_company
  
  def index
    @events = @company.events.all(:order=>"event_date")
  end

  def show
    @event = @company.events.find(params[:id])
  end

  def new
    @event = @company.events.build
    @turnos = @company.bouts.all_active
    @sectors = @company.sectors.all_active
    @insertevents = true
  end

  def create
    @event = @company.events.build(params[:event])
    if @event.save
      #IMPORTA OS FUNCIONARIOS PARA O MODEL PRESENCE
      @sectors = @event.sectors.all
      @present_functionaries = BoutFunctionary.find(:all,
  												    :select=> "`bout_functionaries`.`functionary_id`, `sector_functionaries`.`functionary_id`, `sector_functionaries`.`sector_id`",
  												    :joins=>"INNER JOIN `sector_functionaries` ON `bout_functionaries`.`functionary_id` = `sector_functionaries`.`functionary_id`" ,
  												    :conditions=>['`bout_functionaries`.`start_date` <= ?
                                            AND	((`bout_functionaries`.`end_date` >= ? ) OR `bout_functionaries`.`end_date` is null)
                                            AND `sector_functionaries`.`start_date` <= ?
                                            AND	((`sector_functionaries`.`end_date` >= ? ) OR `sector_functionaries`.`end_date` is null)
                                            AND `bout_functionaries`.`bout_id` = ?
                                            AND `sector_functionaries`.`sector_id` IN (?)' , @event.event_date,@event.event_date,@event.event_date,@event.event_date,@event.bout_id,@sectors.each]
                              )
      @present_functionaries.each do |f|
        @presence = Presence.new
        @presence.functionary_id = f.functionary_id
        @presence.sector_id = f.sector_id
        @presence.event_id = @event.id
        @presence.status_presence_id = STATUS_PRESENCA_PADRAO       
        @presence.save        
      end
    #FIM IMPORTACAO
      
      redirect_to admin_company_event_presences_path(@company,@event), :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
    @event = @company.events.find(params[:id])
    @turnos = @company.bouts.all_active
    @sectors = @company.sectors.all_active
    @insertevents = false
  end

  def update
    @event = @company.events.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to admin_company_event_path(@company, @event), :notice  => "Successfully updated event."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @event = @company.events.find(params[:id])
    @event.destroy
    redirect_to admin_company_events_path(@company), :notice => "Successfully destroyed event."
  end
  
  def load_company
    @company = Company.find(params[:company_id])
  end  
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_form.html.erb
<div id="Box_form">
	<%= form_for [:admin,  @company, @event] do |f| %>
	  <%= f.error_messages %>
	  <p>
	    <%= f.label :event_date, "Aula do dia" %>
	    <%= f.date_select :event_date, { :start_year => 1990, :end_year => Time.now.year} %>
	  </p>
	  <p>
	    <%= f.label :bout_id, "Turno" %>
		<%= f.collection_select :bout_id,@turnos,:id,:name %> 
		<%#= link_to "[ adcionar novo ]",admin_company_bouts_path(@company), :style=>"margin-left: 10px;"%>
	  </p>
	  <p>
	    <%= f.label :observation, "Observações" %><br />
	    <%= f.text_area :observation %>
	  </p>
	<% if @insertevents %>
	<p>
		<% @sectors.each do |sector| %>
		     <%= check_box_tag 'event[sector_ids][]', sector.id, @event.sectors.include?(sector), :class=>"input_radio" %><%= sector.name %><br />
		<% end %>
	</p>
	<% end %>
	  <br />
	  <p><%= submit_tag "Voltar",:type=>"button",:onclick=>"window.open('"+admin_company_events_path(@company)+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%> <%= f.submit "Salvar", :class => "Bt_enviar" %></p>
		<% end %>
	</div>

app/views/admin/events/edit.html.erb
<% title @company.company_name+" - "+ I18n.localize(@event.event_date)+" - "+ @event.bout.name %>

<h1><%= @company.company_name+" - "+ I18n.localize(@event.event_date)+" - "+ @event.bout.name %></h1><br />
<br />
<p>Utilize os campos abaixo para editar as informações do lista de chamada.</p><br />
<br />
<%= render 'form' %>

app/views/admin/events/index.html.erb
<% title @company.company_name+" - Listas de Chamada" %>

<h1><%= @company.company_name %> - Listas de Chamada</h1><br />
<p>Veja as listas de chamada criadas.</p><br />
<p>Para visualziar a lista completa, gere um relatório, <%= link_to "clicando aqui","#"%>.</p><br />
<br />
<p style="text-align: right;"><%= submit_tag "+ Criar novo",:type=>"button",:onclick=>"window.open('"+new_admin_company_event_path(@company)+"','_self');", :class => "Bt_enviar"%> </p>
<br />
<table cellspacing="0" class="tablesorter">
  <thead> 
  <tr>
    <th style="width:40%;">Aula</th>
    <th style="width:30%;">Turno</th>
    <th colspan="3" style="width:30%;">Ações</th>
  </tr>
  </thead> 
  <tbody>
  <% for event in @events %>
    <tr>
      <td><%= I18n.localize(event.event_date) %></td>
      <td><%= event.bout.name %></td>

	  <td><%= link_to "Visualizar", admin_company_event_path(@company,event) %></td>
	  <td><%= link_to "Presenças", admin_company_event_presences_path(@company,event) %></td>	
	  <td><%= link_to "Excluir", admin_company_event_path(@company,event), :confirm => 'Esta operação não poderá ser desfeita, deseja continuar?', :method => :delete %></td>	
	</tr>
  <% end %>
  </tbody>
</table>

app/views/admin/events/new.html.erb
<% title @company.company_name+" - Nova Lista de Chamada" %>

<h1><%= @company.company_name+" - Nova Lista de Chamada" %></h1><br />
<br />
<p>Preencha os campos abaixo para criar uma lista de chamada.</p><br />
<br />
<%= render 'form' %>

app/views/admin/events/show.html.erb
<% title @company.company_name+" - "+ I18n.localize(@event.event_date)+" - "+ @event.bout.name %>

<h1><%= @company.company_name+" - "+ I18n.localize(@event.event_date)+" - "+ @event.bout.name %></h1><br />
<br />
<p>Verifique se as informações abaixo estão corretas.</p><br />
<br />
<p>
  <strong>Aula do dia:</strong>
  <%= I18n.localize(@event.event_date) %>
</p>
<p>
  <strong>Turno:</strong>
  <%= @event.bout.name %>
</p>
<p>
  <strong>Observações:</strong><br />
  <%= @event.observation %>
</p>

<br />
<br />
<br />
<p>
	<%= submit_tag "Voltar",:type=>"button",:onclick=>"window.open('"+admin_company_events_path(@company)+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%>
	<%= submit_tag "Presenças",:type=>"button",:onclick=>"window.open('"+admin_company_event_presences_path(@company,@event)+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%>
</p>