config/routes.rb
KwWellnessfit::Application.routes.draw do


  get "news/index"
  get "news/show"
  get "labors/index"
  get "hints/index"
  get "hints/show"
  get "contacts/new"
  get "contacts/index"
  get "contacts/show"
  post "contacts/create"
  get "clients/index"
  get "cases/index"
  get "cases/show"

 resources :home
 resources :ciafisio
 resources :about
 resources :cases
 resources :works
 resources :links
 
 resources :user_sessions
 resources :users
 resources :password_resets
 resources :atualizar
 
 #Inicio do namespace Admin
 namespace(:admin){
   
   resources :downloads do
     member do
       get :baixar
     end
   end
   resources :presences 
   resources :status_presences   
   resources :companies do #Inicio das rotas vinculadas a companies
     member do
       get 'information'
     end
     resources :functionaries do
       resources :bout_functionaries
       resources :sector_functionaries
     end
     resources :bouts
     resources :sectors  
     resources(:events){
       resources :presences do
        member do
          get 'update_presences'
        end
       end
     }  

   end #Final das rotas vinculadas a companies
   
   resources :static_contents
   resources :users do
     collection do
       get 'search'
     end
   end
   
 
   root :to => "static_contents#index"
 }
 #Final do namespace Admin
 
 root :to => "home#index"
 match 'cadastro' => "users#new"
 match 'login' => 'user_sessions#new'  
 match 'logout' => 'user_sessions#destroy'
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:status_presence/:user_id(.:format)' => 'admin/presences#update_presences'
 
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:blog_id/:user_id', :controller=> 'admin/presences', :action => 'update_presences'
end

app/models/bout.rb
class Bout < ActiveRecord::Base
  belongs_to :company
  has_many :events, :dependent => :destroy
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Bout.all(:conditions => ['active =  true'])
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :functionaries, :dependent => :destroy
  has_many :bouts, :dependent => :destroy
  has_many :sectors, :dependent => :destroy
  has_many :events, :dependent => :destroy  
  #attr_accessible :company_name, :fantasy_name, :cnpj, :phone, :address, :district, :city, :state, :zip_code, :responsible, :segment, :date_visit, :email, :electronic_address, :doctor, :nurse, :security, :engineering, :rh_responsible, :rh_contact, :gymnastics, :reason_gymnastics, :quality, :map, :absenteeism, :rotation, :male_workers, :female_workers, :agreement
end

app/models/download.rb
class Download < ActiveRecord::Base
  #attr_accessible :name, :archive_file_name, :archive_content_type, :archive_file_size, :archive_updated_at
  has_attached_file :archive,
        :url => "/uploads/:attachment/:id/:basename_:style.:extension",
        :path => ":rails_root/public/uploads/:attachment/:id/:basename_:style.:extension"
        
end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :bout_id, :event_date, :employees_present, :observation,  :sector_attributes, :sector_ids
  belongs_to :bout
  belongs_to :company
  has_many :presences
  has_and_belongs_to_many :sectors
end

app/models/functionary.rb
class Functionary < ActiveRecord::Base
  belongs_to :company
  belongs_to :sector
  has_many :presences, :dependent => :destroy
  has_many :bout_functionaries, :dependent => :destroy
  has_many :sector_functionaries, :dependent => :destroy
  #attr_accessible :company_id, :sector_id, :name, :internal_code, :active, :inactivation_date, :reason, :sex
end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :functionary
  belongs_to :event
  belongs_to :status_presence
  belongs_to :sector
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  belongs_to :company
  has_many :functionaries, :dependent => :destroy
  has_many :sector_functionaries
  has_many :bout_functionaries  
  has_many :presences   
  has_and_belongs_to_many :events
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Sector.all(:conditions => ['active = true'])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :empresario
      @role = :empresario
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  def index
  end

  def show
  end

end

app/controllers/rssreader.rb
class RssReader
  require 'rss'
  require 'open-uri'
  def self.posts_for(feed_url, length = 0, perform_validation=false, v_fonte = "")
    posts = []
    open(feed_url) do |rss|
      posts = RSS::Parser.parse(rss, perform_validation).items
    end
    if length > 0
      posts[0..length - 1] if posts.size > length
    else
      posts[0..length - 1]
    end
    
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/hints/index (copy).html.erb
<%content_for :title do%>
	Notícias
<%end%>
<%content_for :head do %>
	<%#= stylesheet_link_tag "cases" %>
	<%#=javascript_include_tag "showcases.js"%>
<%end%>
<div id="Content">
	<div id="Box_left">
		<%=image_tag ("img_dicas.png", :class=>"Img_align") %>
	</div><!-- Box_left end -->
	<div id="Box_right">
		<span class="Breadcrumb"><span class="Breadcrumb"><a href="#">wellness fit</a></span> : <span class="Breadcrumb"><a href="#">notícias</a></span></span>
		<h1 class="Title_internal_box_right">Dicas</h1><br />
		<ul>
			<li class='lista_1'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><%=link_to "Ler mais", hints_show_path %></span></h3>
			</li>
			<li class='lista_2'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_1'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_2'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_1'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_2'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_1'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_2'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
			<li class='lista_1'>
				<h2>08/07/2011 - NOME DA DICA</h2>
				<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus posuere condimentum felis, vel luctus massa suscipit nec. Nullam eget augue elit. - <span class='fonte'>Fonte UOL.</span> <span class='ler_mais'><a href='#'>Ler mais</a></span></h3>
			</li>
		</ul>
	</div><!-- Box_right end -->
	<div class="clear"></div>
</div><!-- Content end -->

app/views/hints/index.html.erb
<%content_for :title do%>
	Dicas :: WellnessFit – O Bem estar em sua melhor forma | Ginástica Laboral e Fisioterapia Corporativa
<%end%>
<%content_for :head do %>
	<%#= stylesheet_link_tag "cases" %>
	<%#=javascript_include_tag "showcases.js"%>
<%end%>
<div id="Content">
	<div id="Box_left">
		<%=image_tag ("img_dicas.png", :class=>"Img_align") %>
	</div><!-- Box_left end -->
	<div id="Box_right">
		<span class="Breadcrumb"><span class="Breadcrumb"><%=link_to "wellness fit", root_path%></span> : <span class="Breadcrumb"><%=link_to "dicas", hints_index_path %></span></span>
		<h1 class="Title_internal_box_right">Dicas</h1><br />
		<ul>
			<li class='lista_1'>
				<h2>01/09/2011 - <b>Setembro</b></h2>
				<h3>
				<br>
				O mês de setembro é um dos melhores meses para variar na alimentação. É o fim do inverno e começo da primavera, momento em que o ar ainda está fresco, mas o frio já não é mais tão intenso. É um dos melhores períodos para escolher frutas, legumes e verduras por um preço bom e com ótima qualidade.<br><br>
Aproveite para intensificar suas atividades físicas. De preferência pela manhã, assim o corpo consegue processar melhor cada exercício e sua disposição para começar o dia melhora muito.<br><br>
No cardápio você pode adicionar frutas da época como morango, caju, mamão Havaí, pera, laranja lima, jabuticaba, goiaba e lima da Pérsia. Além de legumes e verduras como beterraba, chuchu, mandioquinha, pimentão, acelga, alcachofra, brócolis, chicória e couve-flor.
				<br>
				</h3>
			</li>
			
		</ul>
	</div><!-- Box_right end -->
	<div class="clear"></div>
</div><!-- Content end -->

app/views/hints/show.html.erb
<%content_for :title do%>
	Dicas :: WellnessFit – O Bem estar em sua melhor forma | Ginástica Laboral e Fisioterapia Corporativa
<%end%>
<%content_for :head do %>
	<%#= stylesheet_link_tag "cases" %>
	<%#=javascript_include_tag "showcases.js"%>
<%end%>
<div id="Content">
	<div id="Box_left">
		<%=image_tag ("img_dicas.png", :class=>"Img_align") %>
	</div><!-- Box_left end -->
	<div id="Box_right">
		<span class="Breadcrumb"><span class="Breadcrumb"><%=link_to "wellness fit", root_path%></span> : <span class="Breadcrumb"><a href="#">dicas</a></span></span>
		<h1 class="Title_internal_box_right">Dicas</h1><br />
		<p class="Text_internal_box_right">
			Conheça as melhores dicas para aumentar seu rendimento e diminuir a fadiga que a rotina pode causar. Alivie o estresse e aproveite melhor o tempo no trabalho com exercícios e hábitos muito simples, mas com grandes resultados.
		</p>
	</div><!-- Box_right end -->
	<div class="clear"></div>
</div><!-- Content end -->