config/routes.rb
KwWellnessfit::Application.routes.draw do


  get "news/index"
  get "news/show"
  get "labors/index"
  get "hints/index"
  get "hints/show"
  get "contacts/new"
  get "contacts/index"
  get "contacts/show"
  post "contacts/create"
  get "clients/index"
  get "cases/index"
  get "cases/show"

 resources :home
 resources :ciafisio
 resources :about
 resources :cases
 resources :works
 resources :links
 
 resources :user_sessions
 resources :users
 resources :password_resets
 resources :atualizar
 
 #Inicio do namespace Admin
 namespace(:admin){
   
   resources :downloads do
     member do
       get :baixar
     end
   end
   resources :presences 
   resources :status_presences   
   resources :companies do #Inicio das rotas vinculadas a companies
     member do
       get 'information'
     end
     resources :functionaries do
       resources :bout_functionaries
       resources :sector_functionaries
     end
     resources :bouts
     resources :sectors  
     resources(:events){
       resources :presences do
        member do
          get 'update_presences'
        end
       end
     }  

   end #Final das rotas vinculadas a companies
   
   resources :static_contents
   resources :users do
     collection do
       get 'search'
     end
   end
   
 
   root :to => "static_contents#index"
 }
 #Final do namespace Admin
 
 root :to => "home#index"
 match 'cadastro' => "users#new"
 match 'login' => 'user_sessions#new'  
 match 'logout' => 'user_sessions#destroy'
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:status_presence/:user_id(.:format)' => 'admin/presences#update_presences'
 
 
 #match '/admin/companies/:company_id/events/:event_id/presences/:blog_id/:user_id', :controller=> 'admin/presences', :action => 'update_presences'
end

app/models/bout.rb
class Bout < ActiveRecord::Base
  belongs_to :company
  has_many :events, :dependent => :destroy
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Bout.all(:conditions => ['active =  true'])
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :functionaries, :dependent => :destroy
  has_many :bouts, :dependent => :destroy
  has_many :sectors, :dependent => :destroy
  has_many :events, :dependent => :destroy  
  #attr_accessible :company_name, :fantasy_name, :cnpj, :phone, :address, :district, :city, :state, :zip_code, :responsible, :segment, :date_visit, :email, :electronic_address, :doctor, :nurse, :security, :engineering, :rh_responsible, :rh_contact, :gymnastics, :reason_gymnastics, :quality, :map, :absenteeism, :rotation, :male_workers, :female_workers, :agreement
end

app/models/download.rb
class Download < ActiveRecord::Base
  #attr_accessible :name, :archive_file_name, :archive_content_type, :archive_file_size, :archive_updated_at
  has_attached_file :archive,
        :url => "/uploads/:attachment/:id/:basename_:style.:extension",
        :path => ":rails_root/public/uploads/:attachment/:id/:basename_:style.:extension"
        
end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :bout_id, :event_date, :employees_present, :observation,  :sector_attributes, :sector_ids
  belongs_to :bout
  belongs_to :company
  has_many :presences
  has_and_belongs_to_many :sectors
end

app/models/functionary.rb
class Functionary < ActiveRecord::Base
  belongs_to :company
  belongs_to :sector
  has_many :presences, :dependent => :destroy
  has_many :bout_functionaries, :dependent => :destroy
  has_many :sector_functionaries, :dependent => :destroy
  #attr_accessible :company_id, :sector_id, :name, :internal_code, :active, :inactivation_date, :reason, :sex
end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :functionary
  belongs_to :event
  belongs_to :status_presence
  belongs_to :sector
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  belongs_to :company
  has_many :functionaries, :dependent => :destroy
  has_many :sector_functionaries
  has_many :bout_functionaries  
  has_many :presences   
  has_and_belongs_to_many :events
  #attr_accessible :company_id, :name, :description, :active
  
  def self.all_active
    Sector.all(:conditions => ['active = true'])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :empresario
      @role = :empresario
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  layout "inadmin"
  access_control do
      allow :admin 
      allow :supervisor, :empresario, :to =>[:show, :information]
  end
  before_filter :permission_check 

  def index
    #@companies = Company.all
    redirect_to admin_root_path
  end

  def show  
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to [:admin, @company], :notice => "Successfully created company."
    else
      render :action => 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      redirect_to [:admin, @company], :notice  => "Successfully updated company."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to admin_companies_url, :notice => "Successfully destroyed company."
  end
  
  def information
    @company = Company.find(params[:id])
  end
end

app/controllers/rssreader.rb
class RssReader
  require 'rss'
  require 'open-uri'
  def self.posts_for(feed_url, length = 0, perform_validation=false, v_fonte = "")
    posts = []
    open(feed_url) do |rss|
      posts = RSS::Parser.parse(rss, perform_validation).items
    end
    if length > 0
      posts[0..length - 1] if posts.size > length
    else
      posts[0..length - 1]
    end
    
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/companies/_form.html.erb
<div id="Box_form">
<%= form_for [:admin, @company] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :company_name, "Razão Social: "%>
    <%= f.text_field :company_name %>
  </p>
  <p>
    <%= f.label :fantasy_name, "Nome Fantasia: "%>
    <%= f.text_field :fantasy_name %>
  </p>
  <p>
    <%= f.label :cnpj, "CNPJ: "%>
    <%= f.text_field :cnpj %>
  </p>
  <p>
    <%= f.label :phone, "Telefone: "%>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :address, "Endereço: "%>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :district, "Bairro: "%>
    <%= f.text_field :district %>
  </p>
  <p>
    <%= f.label :city, "Cidade: "%>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state, "Estado: "%>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code, "CEP: "%>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :responsible, "Responsável: "%>
    <%= f.text_field :responsible %>
  </p>
  <p>
    <%= f.label :segment, "Segmento: "%>
    <%= f.text_field :segment %>
  </p>
  <p>
    <%= f.label :date_visit, "Data da Visita: "%>
    <%= f.date_select :date_visit %>
  </p>
  <p>
    <%= f.label :email, "E-mail: "%>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :electronic_address, "Endereço Eletrônico: "%>
    <%= f.text_field :electronic_address %>
  </p>
  <p>
    <%= f.label :doctor, "Médico do Trabalho: " %>
    <%= f.text_field :doctor %>
  </p>
  <p>
    <%= f.label :nurse, "Enfermeira do Trabalho: " %>
    <%= f.text_field :nurse %>
  </p>
  <p>
    <%= f.label :security, "Segurança do Trabalho: " %>
    <%= f.text_field :security %>
  </p>
  <p>
    <%= f.label :engineering, "Engenharia: " %>
    <%= f.text_field :engineering %>
  </p>
  <p>
    <%= f.label :rh_responsible, "Responsável: " %>
    <%= f.text_field :rh_responsible %>
  </p>
  <p>
    <%= f.label :rh_contact, "Contato: " %>
    <%= f.text_field :rh_contact %>
  </p>
  <p>
    <%= f.label :gymnastics, "Ginástica Laboral: " %>
	<%= f.radio_button :gymnastics, true, :class=>"input_radio" %>Sim 
	<%= f.radio_button :gymnastics, false, :class=>"input_radio" %>Não
  </p>
  <p>
    <%= f.label :reason_gymnastics, "Por que?: " %><br />
    <%= f.text_area :reason_gymnastics %>
  </p>
  <p>
    <%= f.label :quality, "Há algum trabalho voltado a qualidade de vida? " %><br />
    <%= f.text_area :quality %>
  </p>
  <p>
    <%= f.label :map, "Mapa de risco ou mapeamento. " %><br />
    <%= f.text_area :map %>
  </p>
  <p>
    <%= f.label :absenteeism, "Absenteismo (% relacionados com doenças ocupacionais). " %><br />
    <%= f.text_area :absenteeism %>
  </p>
  <p>
    <%= f.label :rotation, "Turn-Over ou Rotatividade " %><br />
    <%= f.text_area :rotation %>
  </p>
  <p>
    <%= f.label :male_workers, "Funcionários Masculinos: " %>
    <%= f.text_field :male_workers %>
  </p>
  <p>
    <%= f.label :female_workers, "Funcionários Femininos: " %>
    <%= f.text_field :female_workers %>
  </p>
  <p>
    <%= f.label :agreement, "Convênio médico. Qual?" %><br />
    <%= f.text_area :agreement %>
  </p>
  <p><%= submit_tag "Voltar",:type=>"button",:onclick=>"window.open('"+admin_root_path+"','_self');", :class => "Bt_enviar", :style=>"margin-right: 5px;"%> <%= f.submit "Salvar", :class => "Bt_enviar" %></p>
<% end %>
</div>

app/views/admin/companies/edit.html.erb
<% title @company.fantasy_name %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @company] %> |
  <%= link_to "View All", admin_companies_path %>
</p>

app/views/admin/companies/index.html.erb
<% title "Empresas" %>
<table>
  <tr>
    <th>Company Name</th>
    <th>Fantasy Name</th>
    <th>Cnpj</th>
    <th>Phone</th>
    <th>Address</th>
    <th>District</th>
    <th>City</th>
    <th>State</th>
    <th>Zip Code</th>
    <th>Responsible</th>
    <th>Segment</th>
    <th>Date Visit</th>
    <th>Email</th>
    <th>Electronic Address</th>
    <th>Doctor</th>
    <th>Nurse</th>
    <th>Security</th>
    <th>Engineering</th>
    <th>Rh Responsible</th>
    <th>Rh Contact</th>
    <th>Gymnastics</th>
    <th>Reason Gymnastics</th>
    <th>Quality</th>
    <th>Map</th>
    <th>Absenteeism</th>
    <th>Rotation</th>
    <th>Male Workers</th>
    <th>Female Workers</th>
    <th>Agreement</th>
  </tr>
  <% for company in @companies %>
    <tr>
      <td><%= company.company_name %></td>
      <td><%= company.fantasy_name %></td>
      <td><%= company.cnpj %></td>
      <td><%= company.phone %></td>
      <td><%= company.address %></td>
      <td><%= company.district %></td>
      <td><%= company.city %></td>
      <td><%= company.state %></td>
      <td><%= company.zip_code %></td>
      <td><%= company.responsible %></td>
      <td><%= company.segment %></td>
      <td><%= company.date_visit %></td>
      <td><%= company.email %></td>
      <td><%= company.electronic_address %></td>
      <td><%= company.doctor %></td>
      <td><%= company.nurse %></td>
      <td><%= company.security %></td>
      <td><%= company.engineering %></td>
      <td><%= company.rh_responsible %></td>
      <td><%= company.rh_contact %></td>
      <td><%= company.gymnastics %></td>
      <td><%= company.reason_gymnastics %></td>
      <td><%= company.quality %></td>
      <td><%= company.map %></td>
      <td><%= company.absenteeism %></td>
      <td><%= company.rotation %></td>
      <td><%= company.male_workers %></td>
      <td><%= company.female_workers %></td>
      <td><%= company.agreement %></td>
      <td><%= link_to "Show", [:admin, company] %></td>
      <td><%= link_to "Edit", edit_admin_company_path(company) %></td>
      <td><%= link_to "Destroy", [:admin, company], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Company", new_admin_company_path %></p>

app/views/admin/companies/information.html.erb
<% title @company.fantasy_name %>
<%content_for :head do%>
	<%= stylesheet_link_tag "information"%>
<%end%>

<h1><%= @company.company_name %></h1><br />
<p>Bem-vindo ao painel de controle da <%=@company.fantasy_name %>. Clicando nas opções abaixo você poderá atualizar as informações referentes a este cliente.</p>
<div id="options">
	
	
	<div class="box_options">
		<%=link_to(image_tag("bt_adm_info.jpg"), [:admin, @company])%>
		<br />
		<p><%=link_to("Informações",[:admin, @company]) %></p>
	</div>

	<div class="box_options">
		<%=link_to(image_tag("bt_adm_setores.jpg"), admin_company_sectors_path(@company))%>
		<br />
		<p><%=link_to("Setores",admin_company_sectors_path(@company)) %></p>
	</div>
	
	<div class="box_options">
		<%=link_to(image_tag("bt_adm_func.jpg"), admin_company_functionaries_path(@company))%>
		<br />
		<p><%=link_to("Funcionários",admin_company_functionaries_path(@company)) %></p>
	</div>		
	
	<div class="box_options">
		<%=link_to(image_tag("bt_adm_lista.jpg"), admin_company_events_path(@company))%>
		<br />
		<p><%=link_to("Listas de Chamada",admin_company_events_path(@company)) %></p>
	</div>
	
	<div class="box_options">
		<%=link_to(image_tag("bt_adm_relatorio.jpg"),"#", :onclick=>"alert('Este recurso está sendo desenvovido')")%>
		<br />
		<p><%=link_to("Relatórios","#", :onclick=>"alert('Este recurso está sendo desenvovido')") %></p>
	</div>
	
	<div class="clear"></div>
</div>

app/views/admin/companies/new.html.erb
<% title "Nova Empresa" %>

<%= render 'form' %>

app/views/admin/companies/show.html.erb
<h1 class="Form_title">DADOS DA EMRPESA</h1>

<% title @company.fantasy_name %>

<p class="Form_p">
  <strong>Nome da Empresa:</strong>
  <%= @company.company_name %>
</p>
<p class="Form_p">
  <strong>Nome Fantasia:</strong>
  <%= @company.fantasy_name %>
</p>
<p class="Form_p">
  <strong>Segmento:</strong>
  <%= @company.segment %>
</p>
<p class="Form_p">
  <strong>Data da visita:</strong>
  <%= @company.date_visit %>
</p>
<p class="Form_p">
  <strong>Endereço:</strong>
  <%= @company.address %>
</p>
<p class="Form_p">
  <strong>Email:</strong>
  <%= @company.email %>
</p>
<p class="Form_p">
  <strong>Telefone:</strong>
  <%= @company.phone %>
</p>
<p class="Form_p">
  <strong>Endereço eletrônico:</strong>
  <%= @company.electronic_address %>
</p>
<p class="Form_p">
  <strong>Cnpj:</strong>
  <%= @company.cnpj %>
</p>
<p class="Form_p">
  <strong>Distrito:</strong>
  <%= @company.district %>
</p>
<p class="Form_p">
  <strong>Cidade:</strong>
  <%= @company.city %>
</p>
<p class="Form_p">
  <strong>Estado:</strong>
  <%= @company.state %>
</p>
<p class="Form_p">
  <strong>Cep:</strong>
  <%= @company.zip_code %>
</p>
<p class="Form_p">
  <strong>Responsavél:</strong>
  <%= @company.responsible %>
</p>
<p class="Form_p">
  <strong>Médico:</strong>
  <%= @company.doctor %>
</p>
<p class="Form_p">
  <strong>Enfermeiro(a):</strong>
  <%= @company.nurse %>
</p>
<p class="Form_p">
  <strong>Segurança:</strong>
  <%= @company.security %>
</p>
<p class="Form_p">
  <strong>Engenheiro:</strong>
  <%= @company.engineering %>
</p>
<p class="Form_p">
  <strong>Responsável pelo Rh:</strong>
  <%= @company.rh_responsible %>
</p>
<p class="Form_p">
  <strong>Contato do Rh:</strong>
  <%= @company.rh_contact %>
</p>
<h2 class="Form_title2">SOLICITAÇÃO PARA IMPLANTAÇÃO DO PROGRAMA DE GINÁSTICA LABORAL</h2>
<p class="Form_p2">
  <strong>Ginástica:</strong>
  <%= @company.gymnastics %>
</p>
<p class="Form_p2">
  <strong>Motivo da Ginástica:<br /></strong>
  <%= @company.reason_gymnastics %>
</p>
<p class="Form_p2">
  <strong>Qualidade:<br /></strong>
  <%= @company.quality %>
</p>
<p class="Form_p2">
  <strong>Mapa:<br /></strong>
  <%= @company.map %>
</p>
<p class="Form_p2">
  <strong>Absentismo(ociosidade):<br /></strong>
  <%= @company.absenteeism %>
</p>
<p class="Form_p2">
  <strong>Rodízio:<br /></strong>
  <%= @company.rotation %>
</p>
<p class="Form_p2">
  <strong>Funcionários Homens:</strong>
  <%= @company.male_workers %>
</p>
<p class="Form_p2">
  <strong>Funcionárias Mulheres:</strong>
  <%= @company.female_workers %>
</p>
<p class="Form_p2">
  <strong>Contrato:<br /></strong>
  <%= @company.agreement %>
</p>

<p class="Form_buttons">
  <%= link_to "Edit", edit_admin_company_path(@company) %> |
  <%= link_to "Destroy", [:admin, @company], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_companies_path %>
</p>